### ISSUE TITLE
Gitflow feature branches

### ISSUE THREAD

**Issue by wpdevco** [GMBFitness/GMB-Development-Guide#1]
@smonksi: I'm thinking about how we group issues together in our workflow. For example, with Stripe Checkout, we have one big feature and many sub-features. 

When I branch off to start the main feature, I am inclined to branch to `issue/61-checkout-page-requirements`, (or `issue/50-stripe-checkout` ) then commit individual "sub-features" or tasks.

Then, within my `issue/50-stripe-checkout` branch, I might be working on this sub-feature: Show relevant testimonial on checkout #54.

I make a commit and label it like this: 

`issue/54-show-relevant-testimonial-on-checkout [brief description of code completed in this commit]`

This way, you get a self-contained, more or less linear history of the feature as represented by the feature branch.

You may feel differently about this, specifically that we should have unique branches for each and every feature/issue. Keen to hear your thoughts.

Also, do we need to have feature Milestones (in this case it would be "Stripe Checkout")? This would make it easier for the team as whole to get an oversight of feature progress and to contribute.

**Comment by wpdevco** [comment]
The only issue I see is that a sub-feature _could_ have quite a few commits. So it may be better to just label them with a descriptive title/desc and reference the issue # so it links back to it. And then for the final commit, which closes out the issue/feature, instead of: 

> `issue/54-show-relevant-testimonial-on-checkout [brief description of code completed in this commit]`

I would do something like `Checkout testimonials [desc... _Closes_ #54.]` and that way it will reference the issue and automatically [close it](https://help.github.com/articles/closing-issues-via-commit-messages/) when the branch eventually gets merged back into `master` via a `release/`. Does that make sense? 

As for branches, yes, it does make sense to create a (big) feature branch and commit references to individual issues (sub-features).

**Comment by smonksi** [comment]
Yes, that makes a lot of sense. Auto-closing is really good because it gives you a little extra motivation to head towards that final commit!
